# Generated by Django 5.0.6 on 2024-06-19 10:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particular',
            name='nacimiento',
            field=models.DateField(default=datetime.datetime(2006, 6, 19, 10, 32, 14, 488729, tzinfo=datetime.timezone.utc), verbose_name='Fecha nacimiento'),
        ),
    ]
