# Generated by Django 5.0.6 on 2024-06-21 13:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0010_particular_contrasena_particular_contrasena_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particular',
            name='contrasena',
            field=models.CharField(default='12345678aA', max_length=31, unique=True, verbose_name='Contraseña'),
        ),
        migrations.AlterField(
            model_name='particular',
            name='contrasena_2',
            field=models.CharField(default='12345678aA', max_length=31, unique=True, verbose_name='Confirmar contraseña'),
        ),
        migrations.AlterField(
            model_name='particular',
            name='nacimiento',
            field=models.DateField(default=datetime.datetime(2006, 6, 21, 13, 9, 38, 342944, tzinfo=datetime.timezone.utc), verbose_name='Fecha nacimiento'),
        ),
    ]
