# Generated by Django 5.0.6 on 2024-06-21 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0013_alter_particular_contrasena_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particular',
            name='nacimiento',
            field=models.DateField(default=datetime.datetime(2006, 6, 21, 13, 54, 1, 790334, tzinfo=datetime.timezone.utc), verbose_name='Fecha nacimiento'),
        ),
    ]
