# Generated by Django 5.0.6 on 2024-06-21 16:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0017_alter_particular_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particular',
            name='nacimiento',
            field=models.DateField(default=datetime.datetime(2006, 6, 21, 16, 21, 14, 621052, tzinfo=datetime.timezone.utc), verbose_name='Fecha nacimiento'),
        ),
    ]
