# Generated by Django 5.0.6 on 2024-06-22 10:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0019_alter_particular_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='particular',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='particular',
            name='contrasena_2',
        ),
        migrations.RemoveField(
            model_name='particular',
            name='ultima_modificación',
        ),
        migrations.RemoveField(
            model_name='particular',
            name='usuario',
        ),
        migrations.AddField(
            model_name='particular',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='particular',
            name='password',
            field=models.CharField(default='', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='particular',
            name='nacimiento',
            field=models.DateField(default=datetime.datetime(2006, 6, 22, 10, 49, 51, 783832, tzinfo=datetime.timezone.utc), verbose_name='Fecha nacimiento'),
        ),
    ]
