# Generated by Django 5.0.6 on 2024-06-22 10:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0020_remove_particular_contrasena_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='particular',
            name='usuario',
            field=models.CharField(default='', max_length=31, unique=True, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='particular',
            name='nacimiento',
            field=models.DateField(default=datetime.datetime(2006, 6, 22, 10, 58, 49, 585540, tzinfo=datetime.timezone.utc), verbose_name='Fecha nacimiento'),
        ),
    ]
