# Generated by Django 5.0.6 on 2024-06-22 11:08

import datetime
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0021_particular_usuario_alter_particular_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particular',
            name='nacimiento',
            field=models.DateField(default=datetime.datetime(2006, 6, 22, 11, 8, 15, 656158, tzinfo=datetime.timezone.utc), verbose_name='Fecha nacimiento'),
        ),
        migrations.AlterField(
            model_name='particular',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, unique=True, verbose_name='Teléfono'),
        ),
    ]
