# Generated by Django 5.0.6 on 2024-06-22 11:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0022_alter_particular_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particular',
            name='nacimiento',
            field=models.DateField(default=datetime.datetime(2006, 6, 22, 11, 10, 0, 846314, tzinfo=datetime.timezone.utc), verbose_name='Fecha nacimiento'),
        ),
    ]
