# Generated by Django 5.0.6 on 2024-06-23 18:04

import datetime
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0027_alter_particular_options_alter_particular_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='particular',
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='particular',
            name='nacimiento',
            field=models.DateField(default=datetime.datetime(2006, 6, 23, 18, 4, 7, 646052, tzinfo=datetime.timezone.utc), verbose_name='Fecha nacimiento'),
        ),
    ]
