# Generated by Django 5.0.6 on 2024-06-23 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0028_alter_particular_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particular',
            name='nacimiento',
            field=models.DateField(default='', verbose_name='Fecha nacimiento'),
        ),
    ]
