# Generated by Django 5.0.6 on 2024-06-24 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0029_alter_particular_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particular',
            name='nacimiento',
            field=models.DateField(default='timezone.now()-relativedelta(years=18)', verbose_name='Nacimiento'),
        ),
    ]
