# Generated by Django 5.0.6 on 2024-06-24 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0034_alter_particular_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='particular',
            name='nacimiento',
            field=models.DateField(default='', verbose_name='F. Nacimiento'),
        ),
    ]
