# Generated by Django 5.0.6 on 2024-06-24 12:00

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0035_alter_particular_nacimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='particular',
            name='region',
            field=models.CharField(choices=[('ES-C', 'A Coruña [La Coruña]'), ('ES-A', 'Alacant*'), ('ES-AB', 'Albacete'), ('ES-AL', 'Almería'), ('ES-AN', 'Andalucía'), ('ES-VI', 'Araba*'), ('ES-AR', 'Aragón'), ('ES-O', 'Asturias'), ('ES-AS', 'Asturias, Principado de'), ('ES-BA', 'Badajoz'), ('ES-B', 'Barcelona [Barcelona]'), ('ES-BU', 'Burgos'), ('ES-CN', 'Canarias'), ('ES-CB', 'Cantabria'), ('ES-S', 'Cantabria'), ('ES-CS', 'Castelló*'), ('ES-CL', 'Castilla y León'), ('ES-CM', 'Castilla-La Mancha'), ('ES-CT', 'Catalunya [Cataluña]'), ('ES-CE', 'Ceuta'), ('ES-CR', 'Ciudad Real'), ('ES-CU', 'Cuenca'), ('ES-CC', 'Cáceres'), ('ES-CA', 'Cádiz'), ('ES-CO', 'Córdoba'), ('ES-PV', 'Euskal Herria'), ('ES-EX', 'Extremadura'), ('ES-GA', 'Galicia [Galicia]'), ('ES-GI', 'Girona [Gerona]'), ('ES-GR', 'Granada'), ('ES-GU', 'Guadalajara'), ('ES-SS', 'Guipúzcoa'), ('ES-H', 'Huelva'), ('ES-HU', 'Huesca'), ('ES-IB', 'Illes Balears [Islas Baleares]'), ('ES-PM', 'Illes Balears [Islas Baleares]'), ('ES-J', 'Jaén'), ('ES-LO', 'La Rioja'), ('ES-RI', 'La Rioja'), ('ES-GC', 'Las Palmas'), ('ES-LE', 'León'), ('ES-L', 'Lleida [Lérida]'), ('ES-LU', 'Lugo [Lugo]'), ('ES-M', 'Madrid'), ('ES-MD', 'Madrid, Comunidad de'), ('ES-ML', 'Melilla'), ('ES-MU', 'Murcia'), ('ES-MC', 'Murcia, Región de'), ('ES-MA', 'Málaga'), ('ES-NA', 'Nafarroa*'), ('ES-NC', 'Nafarroako Foru Komunitatea*'), ('ES-OR', 'Ourense [Orense]'), ('ES-P', 'Palencia'), ('ES-PO', 'Pontevedra [Pontevedra]'), ('ES-SA', 'Salamanca'), ('ES-TF', 'Santa Cruz de Tenerife'), ('ES-SG', 'Segovia'), ('ES-SE', 'Sevilla'), ('ES-SO', 'Soria'), ('ES-T', 'Tarragona [Tarragona]'), ('ES-TE', 'Teruel'), ('ES-TO', 'Toledo'), ('ES-V', 'Valencia'), ('ES-VC', 'Valenciana, Comunidad'), ('ES-VA', 'Valladolid'), ('ES-BI', 'Vizcaya'), ('ES-ZA', 'Zamora'), ('ES-Z', 'Zaragoza'), ('ES-AV', 'Ávila')], default='ES', max_length=5, verbose_name='Región'),
        ),
        migrations.AlterField(
            model_name='particular',
            name='nacimiento',
            field=models.DateField(default='2006-06-24', verbose_name='F. Nacimiento'),
        ),
        migrations.AlterField(
            model_name='particular',
            name='telefono',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, default='', max_length=128, region=None, verbose_name='Teléfono'),
        ),
    ]
