# Generated by Django 5.0.6 on 2024-06-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0037_usuario_remove_particular_creado_el_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ong',
            name='password1',
        ),
        migrations.RemoveField(
            model_name='ong',
            name='password2',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='nombre',
        ),
        migrations.AddField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(default='', max_length=31, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ong',
            name='nombre',
            field=models.CharField(default='', max_length=31, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='particular',
            name='nombre',
            field=models.CharField(default='', max_length=31, verbose_name='Nombre'),
            preserve_default=False,
        ),
    ]
